name: Auto-commit Activity

on:
  schedule:
    # JANGAN SETIAP MENIT. 
    # Gunakan jadwal teman Anda ('0 1-23 * * *' = setiap jam kecuali jam 00)
    # Atau sekali sehari, misal jam 7 pagi ('0 7 * * *')
    - cron: '0 * * * *' # Ini contoh: berjalan setiap 2 jam

  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode
      - uses: actions/checkout@v4
        with:
          # Perlu token di sini agar push-action bisa menggunakannya
          token: ${{ secrets.GITHUB_TOKEN }} 

      # Langkah 2: Konfigurasi Git (Nama Anda)
      - name: Set up Git
        run: |
          git config --global user.name 'rifalfebiyan'
          git config --global user.email 'rifalfebiyan123@gmail.com'

      # Langkah 3: Membuat Perubahan Palsu (Seperti teman Anda)
      - name: Create Dummy Change
        run: |
          # Perintah ini akan menimpa file 'activity_log.txt' dengan waktu saat ini
          echo "🤖 Activity generated on: $(date)" > activity_log.txt

      # Langkah 4: Commit perubahan
      - name: Commit changes
        run: |
          # Tambahkan semua perubahan (termasuk file activity_log.txt)
          git add -A
          # Buat commit
          git commit -m "Chore(bot): Scheduled auto-commit"
          
      # Langkah 5: Push menggunakan Action Khusus (Paling Penting!)
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          # Pastikan nama branch Anda 'main', bukan 'master'
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}