name: Auto-commit Activity

on:
  schedule:
    # Menjalankan skrip setiap menit
    # PERINGATAN: Ini sangat tidak disarankan. 
    - cron: '* * * * *'
  
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Langkah 2: Konfigurasi Git
      - name: Set up Git
        run: |
          git config --global user.name 'rifalfebiyan'
          git config --global user.email 'rifalfebiyan123@gmail.com'

      # LANGKAH BARU: Membuat perubahan palsu
      - name: Create Dummy Change
        run: |
          # Perintah ini akan menimpa file 'activity_log.txt' dengan waktu saat ini
          # Ini DIJAMIN membuat perubahan file setiap kali skrip jalan
          echo "🤖 Activity generated on: $(date)" > activity_log.txt

      # Langkah 3: Tambah, Commit, dan Push
      - name: Add, Commit, and Push changes
        run: |
          # Hanya tambahkan file spesifik itu, jangan 'git add .'
          git add activity_log.txt
          
          # Commit perubahan
          git commit -m "Chore: Update activity log"
          
          # Dorong (push) perubahan ke branch utama
          git push origin main